### ISSUE TITLE
Best way to do custom bots

### ISSUE THREAD

**Issue by Vexs** [DBDU/union#7]
Part of the idea of this is being able to have quickly deployable bots for individual, user-sided use. Thus, all cogs need to be separable excluding the base bot. This also raises the question of do we want to require users to set up a database and such? 

The config class we end up using could be designed such that we can use a proper database for the public bot, and perhaps json or a smaller, no-dependency database for user-sided stuff. At the same time, this means that the config class is more limited in capability.

**Comment by indiv0** [comment]
As for the deployment process itself, we can automate it with shell scripts for now, and move to a containerized system later on when we need it.

For the storage requirements, I don't think that creating a separate DB per instance would be too much overhead, and I'd prefer to have the option to use a proper relational DB where necessary, instead of attempting to use JSON everywhere.

**Comment by indiv0** [comment]
Reading your post again, I realized I kinda misinterpreted it. I'm not sure if we want to support users running instances themselves.

We kinda have ~~three~~ four possibilities at this point:

1) Run our own, global instance of the bot, selling access to it
2) Run instances for users, providing setup/configuration/support
3) Allow users to run their own instances
4) A "hybrid" approach of 2 & 3

Now, these are not mutually exclusive, and we'll probably doing the first one at least. The question here is do we want to additionally focus on the 2nd option, 3rd option, or both?

If we don't support the 3rd option, but support the 2nd option, this heavily simplifies our need to "dumbify" the codebase, as we don't need to worry about users being able to configure the bot themselves. This means that we can stick with traditional DBs instead of trying to cram everything into JSON. The downside to this is that actually getting this to work is shaky. This is because we'll either need to create many bot accounts ourselves, or ask users to do it and provide their tokens. IIRC this is a violation of Discord ToS, so I'm not sure if it's viable.

If we want to support the 3rd option, this simplifies both the monetisation process and removes the token issues discussed above. This is because we can just sell the whole thing as a pre-packaged "crate" (maybe even sell it as pre-made docker containers). Then all a user has to do buy the pre-made package, provision a VPS, and load the package onto it. Configuration and other things are left to the user, and they're responsible for hosting their instance. The downside to this is that if we want broad appeal, this process needs to be *as simple as possible*.

Now that I think about it, we can also provide a hybrid approach of the 2nd and 3rd options. In a hybrid approach, we can make pre-packaged versions for users, provision the VPS for them, provide configuration/maintenance support, but *also* give users access to the VPS so they can tweak/re-configure it themselves. They would also be responsible for generating and inputting their own tokens, which should get around any ToS issues.

**Comment by indiv0** [comment]
After a cursory review of the ToS actually seems like asking users for tokens would not be a violation, but we would probably want to check with the devs on that.

If this is the case, I think we should prioritize the 2nd approach, as this gives us:

* ability to easily keep instances up-to-date
* ability to modify instances as needed, including changing how/where they're hosted, etc.
* the ability to provide direct support
* avoids giving users the possibility of screwing up the instance/configuration/DB (as would be possible with the 3rd and "hybrid" options)
* saves us from the potential legal issues of hosting/providing VPSes for people

**Comment by DiNitride** [comment]
#2 is the entire concept of the project. Easily deployable bot instances for non-tech people. Union is that bot. Really, the public Union bot is just a instance of this, how a client would have it, with access to everything

**Comment by indiv0** [comment]
Yeah I agree. I just listed out the other options because I saw people discussing vaguely similar approaches in the chat and wanted to clarify the differences between them.

👍 for the 2nd approach.

**Comment by Vexs** [comment]
Yeah, the original idea was that we basically sell off custom bots/cogs at a decent price, as well as being able to host for a small monthly fee. Union serves as the "core" bot for people that are happy with not requiring their own instance of the bot, and will also have all our cogs.

**Comment by indiv0** [comment]
Except that the private cogs on the core bot will only be enabled on pre-approved servers to avoid everyone using the core bot to get the features for free.

**Comment by DiNitride** [comment]
Righto, the entire concept of this, in my head

"I want a unique bot for my community, however I can't program and don't have the technical abilities to host one myself" - A Client

Our service offers an easy way to get a private bot, hosted by us, with an easy way of managing it. The client provides the login token, and we do the rest. So what happens when a user buys an instance?

First of all, the user sets a name, icon, prefix and provides the login token. Then, hit deploy! On deploy, on our end, the instance is created. This is a self-contained, entirely independant instance of Union, that loads the cogs that have been purchased, and has it's own storage. 

Then, their bot is booted, and they can invite it to any number of servers (Up to the amount they have payed for)

Union, is both the public bot and the bot base that is loaded as an instance. In fact, the public bot is just an instance of it, as if we were the clients. Union needs to start, load the cogs that are purchased by it's owner (Loaded from the DB), and then run those cogs. It is small, simple, yet easy to use. Just copy the code in, and it will run. 

The public Union bot will be an instance, with a few cogs enabled to demonstrate the power of the bot.

The idea is not a public, modular bot, this could maybe come later, the idea is a system that allows easy, one click setup, hosting, and support.
